src/main/java/model/Category.java
package model;

public class Category {
    private long id;
    private String name;

    public Category() {
    }

    public Category(long id, String name) {
        this.id = id;
        this.name = name;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}

src/main/java/model/Event.java
package model;

import java.time.LocalDate;
import java.util.List;

public class Event {
    private long id;
    private String name;
    private LocalDate date;
    private String contact_number;
    private Long id_category;
    private String description;
    private String urlImage;
    private String category;
    private List<HashTag> tags;


    public Event() {
    }

    public Event(long id, String name, LocalDate date, String contact_number, Long id_category, String description, String urlImage) {
        this.id = id;
        this.name = name;
        this.date = date;
        this.contact_number = contact_number;
        this.id_category = id_category;
        this.description = description;
        this.urlImage = urlImage;
    }

    public Event(long id, String name, LocalDate date, String contact_number, Long id_category, String description, String urlImage, String category, List<HashTag> tags) {
        this.id = id;
        this.name = name;
        this.date = date;
        this.contact_number = contact_number;
        this.id_category = id_category;
        this.description = description;
        this.urlImage = urlImage;
        this.category = category;
        this.tags = tags;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public LocalDate getDate() {
        return date;
    }

    public void setDate(LocalDate date) {
        this.date = date;
    }

    public String getContactTelNum() {
        return contact_number;
    }

    public void setContactTelNum(String contact_number) {
        this.contact_number = contact_number;
    }

    public Long getIdCategory() {
        return id_category;
    }

    public void setIdCategory(Long id_category) {
        this.id_category = id_category;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getUrlImage() {
        return urlImage;
    }

    public void setUrlImage(String urlImage) {
        this.urlImage = urlImage;
    }

    public List<HashTag> getTags() {
        return tags;
    }

    public void setTags(List<HashTag> tags) {
        this.tags = tags;
    }


    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

}

src/main/java/model/HashTag.java
package model;

public class HashTag {
    private long id;
    private String name;

    public HashTag() {
    }

    public HashTag(long id, String name) {
        this.id = id;
        this.name = name;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}

src/main/java/servlet/AddCategoryServlet.java
package servlet;

import model.Category;
import service.CategoryServiceImp;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;

@WebServlet(name = "AddCategoryServlet", urlPatterns = "/addCategory")
public class AddCategoryServlet extends HttpServlet {
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        CategoryServiceImp categoryServiceImp = new CategoryServiceImp();
        Category category = new Category();
        category.setName(request.getParameter("name"));
        try {
            categoryServiceImp.createCategory(category);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        RequestDispatcher requestDispatcher = request.getRequestDispatcher("index.jsp");
        requestDispatcher.include(request, response);
    }
}

src/main/java/servlet/AddEventServlet.java
package servlet;

import model.Category;
import model.Event;
import model.HashTag;
import service.CategoryServiceImp;
import service.EventServiceImpl;
import service.HashTagImp;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Arrays;
import java.util.List;

@WebServlet(name = "AddEvent", urlPatterns = "/addEvent")
public class AddEventServlet extends HttpServlet {

    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
HashTagImp hashTagImp = new HashTagImp();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("uuuu-MM-dd");
        String date = String.format(request.getParameter("date"), formatter);
        EventServiceImpl eventService = new EventServiceImpl();
        Event event = new Event();
        event.setName(request.getParameter("name"));
        event.setDate(LocalDate.parse(request.getParameter("date")));

        event.setUrlImage(request.getParameter("url_image"));
        event.setContactTelNum(request.getParameter("contact_number"));
        String[] hashes = request.getParameterValues("hashes");
        List<HashTag> hashTags = null;
        try {

            hashTags = hashTagImp.getHashesList(Arrays.asList(hashes));
        } catch (SQLException e) {

            response.sendRedirect(request.getContextPath() + "/error?type=general");

        }
        try {
            event.setIdCategory(Long.parseLong(request.getParameter("id_category")));
        } catch (Exception e) {
            e.printStackTrace();

        }
        event.setTags(hashTags);
        event.setDescription(request.getParameter("description"));
        try {
            eventService.createEvent(event);
        } catch (Exception e) {
            e.printStackTrace();

        }
        response.sendRedirect(request.getContextPath()+"/blog");
    }

    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        HashTagImp hashTagImp = new HashTagImp();


        try {
            List<HashTag> hashes = hashTagImp.findAll();
            request.setAttribute("hashes", hashes);
        } catch (Exception e) {
            e.printStackTrace();
        }
        CategoryServiceImp categoryServiceImp = new CategoryServiceImp();
        try {

            List<Category> categories = categoryServiceImp.getAll();
            request.setAttribute("categories", categories);
        } catch (Exception e) {
            e.printStackTrace();
        }
        RequestDispatcher requestDispatcher = request.getRequestDispatcher("index.jsp");
        requestDispatcher.include(request, response);
    }
}

src/main/java/servlet/AllEventsServlet.java
package servlet;

import model.Event;
import service.EventServiceImpl;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.List;

@WebServlet(name = "AllEventsServlet", urlPatterns = "/blog")
public class AllEventsServlet extends HttpServlet {
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {

    }

        protected void doGet (HttpServletRequest request, HttpServletResponse response) throws
        ServletException, IOException {
           EventServiceImpl eventService= new EventServiceImpl();

            try {
                List<Event> events = eventService.getAll();
                request.setAttribute("events", events);
            } catch (Exception e) {
                e.printStackTrace();
            }

            RequestDispatcher requestDispatcher = request.getRequestDispatcher("blog.jsp");
            requestDispatcher.include(request, response);
        }

    }

src/main/java/servlet/DeleteEventServlet.java
package servlet;

import service.EventServiceImpl;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;

@WebServlet(name = "DeleteEventServlet", urlPatterns = "/delete")
public class DeleteEventServlet extends HttpServlet {
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {

    }

    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        EventServiceImpl eventService = new EventServiceImpl();
        Long id = Long.valueOf(request.getParameter("id"));
        try {
            eventService.deletePost(id);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        RequestDispatcher requestDispatcher = request.getRequestDispatcher("blog.jsp");
        requestDispatcher.include(request, response);
        response.sendRedirect(request.getContextPath()+"/blog");
    }
}

src/main/java/servlet/EditEventServlet.java
package servlet;

import model.Category;
import model.Event;
import model.HashTag;
import service.CategoryServiceImp;
import service.EventServiceImpl;
import service.HashTagImp;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;

@WebServlet(name = "EditEventServlet", urlPatterns = "/editEvent")
public class EditEventServlet extends HttpServlet {
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {

        Event event = new Event();
        HashTagImp hashTagImp = new HashTagImp();
        EventServiceImpl eventService = new EventServiceImpl();

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("uuuu-MM-dd");
        String date = String.format(request.getParameter("date"), formatter);

        event.setId(Long.valueOf(request.getParameter("id")));
        event.setName(request.getParameter("name"));
        event.setDate(LocalDate.parse(request.getParameter("date")));

        event.setUrlImage(request.getParameter("url_image"));
        event.setContactTelNum(request.getParameter("contact_number"));


        try {

            List<HashTag> hashTags = eventService.getEventById(Long.valueOf(request.getParameter("id"))).getTags();
            request.setAttribute("hashes", hashTags);
            event.setTags(hashTags);
        } catch (Exception e) {
            e.printStackTrace();
        }

        try {
            event.setIdCategory(Long.parseLong(request.getParameter("id_category")));
        } catch (Exception e) {
            e.printStackTrace();

        }

        event.setDescription(request.getParameter("description"));
        try {
            eventService.updateEvent(event);
        } catch (Exception e) {
            e.printStackTrace();

        }
        response.sendRedirect(request.getContextPath() + "/blog");

        RequestDispatcher requestDispatcher = request.getRequestDispatcher("editEvent.jsp");
        requestDispatcher.include(request, response);
    }


    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        CategoryServiceImp categoryServiceImp = new CategoryServiceImp();
        EventServiceImpl eventService = new EventServiceImpl();
        HashTagImp hashTagImp = new HashTagImp();
        try {

            List<Category> categories = categoryServiceImp.getAll();
            request.setAttribute("categories", categories);
        } catch (Exception e) {
            e.printStackTrace();
        }


        Event event = new Event();
        try {
            event = eventService.getEventById(Long.parseLong(request.getParameter("id")));

        } catch (Exception e) {
            e.printStackTrace();
        }

        try {

            List<HashTag> hashTags = eventService.getEventById(Long.valueOf(request.getParameter("id"))).getTags();
            request.setAttribute("hashes", hashTags);
            event.setTags(hashTags);
        } catch (Exception e) {
            e.printStackTrace();
        }

        System.out.println();
        request.setAttribute("event", event);

        RequestDispatcher requestDispatcher = request.getRequestDispatcher("editEvent.jsp");
        requestDispatcher.include(request, response);

    }
}

src/main/java/servlet/SearchServlet.java
package servlet;

import model.Category;
import model.Event;
import service.CategoryServiceImp;
import service.EventServiceImpl;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;

@WebServlet(name = "SearchServlet", urlPatterns = "/search")
public class SearchServlet extends HttpServlet {
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {

        EventServiceImpl eventService = new EventServiceImpl();
        List<Event> events = null;
        String name = request.getParameter("name_find");
        String descr = request.getParameter("description");
        if (!Objects.equals(request.getParameter("name_find"), "")) {
            try {
                events = eventService.findByName(name);
                if(!descr.equals(""))
                    events = events.stream().filter(e->e.getDescription().contains(descr)).collect(Collectors.toList());
                request.setAttribute("events", events);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

        RequestDispatcher requestDispatcher = request.getRequestDispatcher("blog.jsp");
        requestDispatcher.include(request, response);
    }


    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {


        CategoryServiceImp categoryServiceImp = new CategoryServiceImp();
        try {

            List<Category> categories = categoryServiceImp.getAll();
            request.setAttribute("categories", categories);
        } catch (Exception e) {
            e.printStackTrace();
        }

        RequestDispatcher requestDispatcher = request.getRequestDispatcher("search.jsp");
        requestDispatcher.include(request, response);


    }
}

src/main/java/servlet/Servlet.java
package servlet;

import model.Event;
import service.EventServiceImpl;

import javax.servlet.RequestDispatcher;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.List;

@WebServlet(name = "Servlet", urlPatterns = "/addUser")
public class Servlet extends HttpServlet {
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws javax.servlet.ServletException, IOException {

    }

    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws javax.servlet.ServletException, IOException {
        EventServiceImpl eventService = new EventServiceImpl();

        try {

            List<Event> events = eventService.getAll();
            request.setAttribute("events", events);
        } catch (Exception e) {
            e.printStackTrace();
        }

        RequestDispatcher requestDispatcher = request.getRequestDispatcher("index.jsp");

        requestDispatcher.forward(request, response);
    }
}

src/main/webapp/blog.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<link rel="stylesheet" href="style.css" style="background-color: lightgray">

<head>
    <title>Blog</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
</head>
<html>
<body style="background-image: url(http://www.ohphoto.com.au/gallery/original/Grey-gradient_3.jpg)">

<ul class="nav nav-tabs" style="background-color: #272125; text-decoration-color: whitesmoke">
    <li class="nav-item ">
        <a class="nav-link active" href="${pageContext.request.contextPath}/blog">BLOG</a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="${pageContext.request.contextPath}/addEvent">Add event</a>
    </li>
</ul>
<form action="${pageContext.request.contextPath}/search" method="post">

<input name = "name_find"  type="text" placeholder="find by name">
    <input name = "description"  type="text" placeholder="description">
    <input type="submit" value="search"></form>
<form action="${pageContext.request.contextPath}/blog" method="post" class="mx-auto" style="width: 600px; ">
    <div class="card" style="max-width: 1200px;   margin: auto">

        <c:forEach items="${events}" var="event">
            <div class="row" style="width: 600px">
              <div></div>
                <div class="card" style="width: 5200px;  background-color: dimgray">
                    <img class="card-img-top" src="im.jpg" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">${event.name}<br>${event.date}</h5>
                        <p class="card-text">${event.description}</p>
                        <p>${event.category}</p>
                        <c:forEach items="${event.tags}" var = "tag">
                        #${tag.name}</c:forEach>
                        <a href=${pageContext.request.contextPath}/editEvent?id=${event.id}
                           class="btn btn-primary">Edit</a>
                        <a href="${pageContext.request.contextPath}/delete?id=${event.id}" class="btn btn-primary">Delete</a>
                    </div>
                </div>
            </div>
        </c:forEach></div>
    <!--add new event-->
    <div class="card" style="width: 26rem;">

    </div>
    </div>
    </div>
    </div>
</form>

</body>
</html>

src/main/webapp/editEvent.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<head>
    <link rel="stylesheet" href="style.css">
</head>
<form action="${pageContext.request.contextPath}/editEvent?id=${event.id}" method="post" style="width : 320px;">
    <input type = "text" name = "id" value="${event.id}">

    <div class="form-group">
        <h2 >Name of event :</h2>
        <input type="text" class="form-control" name="name" value="${event.name}">
    </div>
    <div class="form-group">
        <h2 >contact number</h2>
        <input type="text" class="form-control" name="contact_number"  value="${event.contactTelNum}">
    </div>
    <div class="form-group">
        <h2 > Date of event</h2>
        <input type="date" class="form-control" name="date" value="${event.date}">
    </div>
    <div class="form-group">
        <h2 > Category</h2>
        <input type="text" class="form-control" name="id_category">
    </div>
    <h2>hashes</h2>
    <select required multiple class="form-control" name="hashes" style="height: 90px">
        <c:forEach items="${requestScope.hashes}" var = "tag">
            <option value="${tag.name}">${tag.name}</option>
        </c:forEach>
    </select><br>

    <div class="form-group">
        <h2 >description</h2>
        <input type="text" class="form-control" name="description" value="${event.description}">
    </div>
    <button type="submit"><a href="${pageContext.request.contextPath}/blog"></a>save</button>
</form>

src/main/webapp/getEvent.jsp
<%--
  Created by IntelliJ IDEA.
  User: atymottc
  Date: 27.06.2019
  Time: 14:14
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>Title</title>
</head>
<body>

</body>

</html>

src/main/webapp/index.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<head>
    <link rel="stylesheet" href="style.css">
    <link  href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
    <script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.js"></script>
</head>
<script>
    $('.ui.fluid.search.dropdown')
        .dropdown({
            allowAdditions: true
        })
    ;
</script>
<form action="${pageContext.request.contextPath}/addEvent" method="post" style="width : 320px;">

    <h2>Event name</h2>
    <input type="text" class="form-control" name="name" placeholder="event...">
    </div>
    <div class="form-group">
        <h2>Date of event</h2>
        <input type="date" class="form-control" name="date">
    </div>
    <div class="form-group">
        <h2>contact number</h2>
        <input type="text" class="form-control" name="contact_number" placeholder="+ 38(097) - *** - *** - **">
    </div>
    <div class="form-group">
        <h2>category</h2>
        <select name="id_category">
            <c:forEach items="${categories}" var="category">
                <option value="${category.id}">${category.name}</option>
            </c:forEach>
        </select>
        <div class="form-group">
            <h2>hashes</h2>
            <select required multiple class="form-control" name="hashes" style="height: 90px">
                <c:forEach items="${hashes}" var="hash">
                    <option class="form-control" style="width: 150px" value=${hash.id}>${hash.name}</option>
                </c:forEach>
            </select><br>
        </div>
        <h2>description</h2>
        <input type="text" class="form-control" name="description" placeholder="text">
    </div>
    <button type="submit">ok</button>
</form>

src/main/webapp/search.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<link rel="stylesheet" href="style.css" style="background-color: lightgray">

<head>
    <title>Blog</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
</head>
<html>
<body style="background-image: url(http://www.ohphoto.com.au/gallery/original/Grey-gradient_3.jpg)">

<ul class="nav nav-tabs" style="background-color: #272125; text-decoration-color: whitesmoke">

    <ul class="nav nav-tabs" style="background-color: #272125; text-decoration-color: whitesmoke">
        <li class="nav-item ">
            <a class="nav-link " href="${pageContext.request.contextPath}/blog">BLOG</a>
        </li>
        <li class="nav-item ">
            <a class="nav-link active" href="${pageContext.request.contextPath}/search">Search</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="${pageContext.request.contextPath}/addEvent">Add event</a>
        </li>
        <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1"
               href="${pageContext.request.contextPath}/SignIn">LogOut</a>
        </li>
    </ul>
</ul>
<form action="${pageContext.request.contextPath}/search" method="post" style="width : 320px;">
    <h1>Input fields </h1>
    <div></div>
    <h3>Event name</h3>
    <input type="text" class="form-control" name="name_find" placeholder="event...">
    </div>

    <div class="form-group">
        <div><h2>category</h2>
            <select name="id_category">
                <c:forEach items="${categories}" var="category">
                <option value="${category.id}">${category.name}</option>
                </c:forEach>
        </div>
        <div>     <div></div>
            <h2>description</h2>
            <input type="text" class="form-control" name="description" placeholder="text">
        </div>
    </div>
    <button type="submit">find</button>
</form>
</body>
</html>

src/main/webapp/signIn.jsp
<link rel="stylesheet" href="style.css">
<form action="${pageContext.request.contextPath}/signIn" method="post" style="width : 320px;">
    <h2 class="login" class="fa fa-sign-in"> Login</h2>
    <input type="text" name="user_name" class="user" placeholder="ursername"/>
    <input type="password" name="password" class="pass" placeholder="password"/>
    <button class="submit"><a href="${pageContext.request.contextPath}/blog?user_name=${user_name}"></a>IN</button>
    <a href="${pageContext.request.contextPath}/signUp">SignUp</a>
</form>

src/main/webapp/signUp.jsp
<link rel="stylesheet" href="style.css" >

<form action="${pageContext.request.contextPath}/signUp" method="post" style="width : 320px;" >
    <h2><span class="entypo-login"><i class="fa fa-sign-in"></i></span> SignUp</h2>

    <input type="text" name="user_name" class="name" placeholder="username"/>
    <input type="email" name="email" class="email" placeholder="email"/>
    <input type="password" name ="password" class="pass"placeholder="password"/>
    <input type="password" name = "confPassword" class="pass"placeholder="confirm password"/>
    <button class="submit" type="submit"></button>
</form>>